gg_list[0]=[{num:1,level:1,sp_name:'Fish',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[0].push({num:2,level:1,sp_name:'Fish',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "`|SNybk-W6Th:d_9]8$^"]},fields:{}});
gg_list[0].push({num:3,level:1,sp_name:'Fish',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [1, [4, "5"]]},fields:{}});
gg_list[0].push({num:4,level:1,sp_name:'Fish',code:'motion_ifonedgebounce',one_hot:15,inputs:{},fields:{}});
gg_list[1]=[{num:5,level:1,sp_name:'Shark',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[1].push({num:6,level:1,sp_name:'Shark',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [3, "cRcs.W_lwVp8zo%rTSGG", null]},fields:{}});
gg_list[1].push({num:7,level:1,sp_name:'Shark',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [1, [4, "10"]]},fields:{}});
gg_list[1].push({num:8,level:1,sp_name:'Shark',code:'motion_ifonedgebounce',one_hot:15,inputs:{},fields:{}});
gg_list[2]=[{num:9,level:1,sp_name:'Jellyfish',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[2].push({num:10,level:1,sp_name:'Jellyfish',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [3, "?2lVM11ac=6uFlEG)%;t", null]},fields:{}});
gg_list[2].push({num:11,level:1,sp_name:'Jellyfish',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [1, [4, "2"]]},fields:{}});
gg_list[2].push({num:12,level:1,sp_name:'Jellyfish',code:'motion_ifonedgebounce',one_hot:15,inputs:{},fields:{}});
gg_list[3]=[{num:13,level:2,sp_name:'Nemo',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[3].push({num:14,level:2,sp_name:'Nemo',code:'motion_turnright',one_hot:3,inputs:{"DEGREES": [1, [4, "15"]]},fields:{}});
gg_list[4]=[{num:15,level:2,sp_name:'Nemo',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "8)`5g2+O:/5l7~vjUBp*"]},fields:{"MOTIONSEL": ["7", null]}}];
gg_list[4].push({num:16,level:2,sp_name:'Nemo',code:'looks_cleargraphiceffects',one_hot:32,inputs:{},fields:{}});
gg_list[5]=[{num:17,level:2,sp_name:'Nemo',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD2", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[5].push({num:18,level:2,sp_name:'Nemo',code:'looks_hide',one_hot:34,inputs:{},fields:{}});
gg_list[5].push({num:19,level:2,sp_name:'Nemo',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "1"]]},fields:{}});
gg_list[5].push({num:20,level:2,sp_name:'Nemo',code:'looks_show',one_hot:33,inputs:{},fields:{}});
gg_list[6]=[{num:21,level:2,sp_name:'Nemo',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD3", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[6].push({num:22,level:2,sp_name:'Nemo',code:'looks_changeeffectby',one_hot:30,inputs:{"CHANGE": [1, [4, "25"]]},fields:{"EFFECT": ["COLOR", null]}});
gg_list[7]=[{num:23,level:2,sp_name:'Nemo',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD4", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[7].push({num:24,level:2,sp_name:'Nemo',code:'looks_changeeffectby',one_hot:30,inputs:{"CHANGE": [1, [4, "25"]]},fields:{"EFFECT": ["WHIRL", null]}});
gg_list[8]=[{num:25,level:3,sp_name:'Bear-walking',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[8].push({num:26,level:3,sp_name:'Bear-walking',code:'looks_nextcostume',one_hot:25,inputs:{},fields:{}});
gg_list[8].push({num:27,level:3,sp_name:'Bear-walking',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [1, [4, "10"]]},fields:{}});
gg_list[8].push({num:28,level:3,sp_name:'Bear-walking',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "0.5"]]},fields:{}});
gg_list[8].push({num:29,level:3,sp_name:'Bear-walking',code:'motion_ifonedgebounce',one_hot:15,inputs:{},fields:{}});
gg_list[9]=[{num:30,level:3,sp_name:'Avery Walking',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[9].push({num:31,level:3,sp_name:'Avery Walking',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "r^TY+,APw*zwuLx[:+xR"]},fields:{}});
gg_list[9].push({num:32,level:3,sp_name:'Avery Walking',code:'looks_nextcostume',one_hot:25,inputs:{},fields:{}});
gg_list[9].push({num:33,level:3,sp_name:'Avery Walking',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [1, [4, "7"]]},fields:{}});
gg_list[9].push({num:34,level:3,sp_name:'Avery Walking',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "0.3"]]},fields:{}});
gg_list[9].push({num:35,level:3,sp_name:'Avery Walking',code:'motion_ifonedgebounce',one_hot:15,inputs:{},fields:{}});
gg_list[10]=[{num:36,level:3,sp_name:'Unicorn Running',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[10].push({num:37,level:3,sp_name:'Unicorn Running',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "E/BgEerb_iDzNa#,6iKt"]},fields:{}});
gg_list[10].push({num:38,level:3,sp_name:'Unicorn Running',code:'looks_nextcostume',one_hot:25,inputs:{},fields:{}});
gg_list[10].push({num:39,level:3,sp_name:'Unicorn Running',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [1, [4, "12"]]},fields:{}});
gg_list[10].push({num:40,level:3,sp_name:'Unicorn Running',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "0.3"]]},fields:{}});
gg_list[10].push({num:41,level:3,sp_name:'Unicorn Running',code:'motion_ifonedgebounce',one_hot:15,inputs:{},fields:{}});
gg_list[11]=[{num:42,level:3,sp_name:'Giraffe',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[11].push({num:43,level:3,sp_name:'Giraffe',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "d7Jg@/+.;-1X!W%n/Iy@"]},fields:{}});
gg_list[11].push({num:44,level:3,sp_name:'Giraffe',code:'looks_nextcostume',one_hot:25,inputs:{},fields:{}});
gg_list[11].push({num:45,level:3,sp_name:'Giraffe',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [1, [4, "12"]]},fields:{}});
gg_list[11].push({num:46,level:3,sp_name:'Giraffe',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "0.5"]]},fields:{}});
gg_list[11].push({num:47,level:3,sp_name:'Giraffe',code:'motion_ifonedgebounce',one_hot:15,inputs:{},fields:{}});
gg_list[12]=[{num:48,level:4,sp_name:'Nemo Face',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[12].push({num:49,level:4,sp_name:'Nemo Face',code:'probo_cube_picker',one_hot:121,inputs:{"CUBE_LED_DATA": [1, "Kq+-cX3o-54hkM|B{=|["], "CUBE_SPEEDS": [1, "vBr6a2VMf@Sv?HjUq1^["]},fields:{"CUBE_SPEEDS": ["0", null],"PICKER": ["2046210121462000000000000000", null]}});
gg_list[12].push({num:50,level:4,sp_name:'Nemo Face',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "*iDx4vLx)peUe`n5Rs}c"]},fields:{"COSTUME": ["Nemo Face", null]}});
gg_list[13]=[{num:51,level:4,sp_name:'Nemo Face',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD2", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[13].push({num:52,level:4,sp_name:'Nemo Face',code:'probo_cube_picker',one_hot:121,inputs:{"CUBE_LED_DATA": [1, "|^YmG;;Vm[ATa[@,k-]*"], "CUBE_SPEEDS": [1, "RuPQOqF8}_I@tSI/6HCX"]},fields:{"CUBE_SPEEDS": ["0", null],"PICKER": ["4021020202214000000000000000", null]}});
gg_list[13].push({num:53,level:4,sp_name:'Nemo Face',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "KjzA(M)rTa=_iG.Uo*6="]},fields:{"COSTUME": ["Nemo Face2", null]}});
gg_list[14]=[{num:54,level:4,sp_name:'Nemo Face',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD3", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[14].push({num:55,level:4,sp_name:'Nemo Face',code:'probo_cube_picker',one_hot:121,inputs:{"CUBE_LED_DATA": [1, "l#Q+[2vy^ASJnqF`U|s|"], "CUBE_SPEEDS": [1, ".+ya{F%P%i%gi}H{%1vH"]},fields:{"CUBE_SPEEDS": ["0", null],"PICKER": ["2070230323702000000000000000", null]}});
gg_list[14].push({num:56,level:4,sp_name:'Nemo Face',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "$xdIJ+m1/2[CiJs{j3^I"]},fields:{"COSTUME": ["Nemo Face3", null]}});
gg_list[15]=[{num:57,level:4,sp_name:'Nemo Face',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD4", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[15].push({num:58,level:4,sp_name:'Nemo Face',code:'probo_cube_picker',one_hot:121,inputs:{"CUBE_LED_DATA": [1, ";^oU6nuDh$LCDy*]T+`L"], "CUBE_SPEEDS": [1, "[3v.f@C-QqFh#SDG6x.L"]},fields:{"CUBE_SPEEDS": ["0", null],"PICKER": ["203f2202223f2000000000000000", null]}});
gg_list[15].push({num:59,level:4,sp_name:'Nemo Face',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "m1atI;F@fJ-T`ZR~RQkB"]},fields:{"COSTUME": ["Nemo Face4", null]}});
gg_list[16]=[{num:60,level:4,sp_name:'Nemo Face',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "$C^50d]g6[}r0#dyc.:~"]},fields:{"MOTIONSEL": ["4", null]}}];
gg_list[16].push({num:61,level:4,sp_name:'Nemo Face',code:'probo_cube_picker',one_hot:121,inputs:{"CUBE_LED_DATA": [1, ";jqG:b1G.yT3U3fJMC4`"], "CUBE_SPEEDS": [1, "R.]$l2{dd/hGz(!%ikAZ"]},fields:{"CUBE_SPEEDS": ["0", null],"PICKER": ["1010040c04101000000000000000", null]}});
gg_list[16].push({num:62,level:4,sp_name:'Nemo Face',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "ULNRdCajn-tippUf@?cs"]},fields:{"COSTUME": ["Nemo Face5", null]}});
gg_list[17]=[{num:63,level:5,sp_name:'02-6네모보드1',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "X+i{Sn:Q:{=Lw-=i#Fo;"]},fields:{"MOTIONSEL": ["3", null]}}];
gg_list[17].push({num:64,level:5,sp_name:'02-6네모보드1',code:'motion_changexby',one_hot:11,inputs:{"DX": [1, [4, "10"]]},fields:{}});
gg_list[18]=[{num:65,level:5,sp_name:'02-6네모보드1',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "~(G.jXA!s+~LqXP;(CM{"]},fields:{"MOTIONSEL": ["2", null]}}];
gg_list[18].push({num:66,level:5,sp_name:'02-6네모보드1',code:'motion_changexby',one_hot:11,inputs:{"DX": [1, [4, "-10"]]},fields:{}});
gg_list[19]=[{num:67,level:5,sp_name:'02-6네모보드1',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "ujpu_Kk,j`/W]e2SHmv["]},fields:{"MOTIONSEL": ["0", null]}}];
gg_list[19].push({num:68,level:5,sp_name:'02-6네모보드1',code:'motion_changeyby',one_hot:13,inputs:{"DY": [1, [4, "10"]]},fields:{}});
gg_list[20]=[{num:69,level:5,sp_name:'02-6네모보드1',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "C7K7#jUI#(PijZ.I?Jf0"]},fields:{"MOTIONSEL": ["1", null]}}];
gg_list[20].push({num:70,level:5,sp_name:'02-6네모보드1',code:'motion_changeyby',one_hot:13,inputs:{"DY": [1, [4, "-10"]]},fields:{}});
gg_list[21]=[{num:71,level:5,sp_name:'Cloud',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[21].push({num:72,level:5,sp_name:'Cloud',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "[)jq/A*FfTmQI!WGD/Vj"]},fields:{}});
gg_list[21].push({num:73,level:5,sp_name:'Cloud',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [1, [4, "2"]]},fields:{}});
gg_list[21].push({num:74,level:5,sp_name:'Cloud',code:'motion_ifonedgebounce',one_hot:15,inputs:{},fields:{}});
gg_list[22]=[{num:75,level:5,sp_name:'Clouds',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[22].push({num:76,level:5,sp_name:'Clouds',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "meT!S9}o:B(uQv(ZWO*F"]},fields:{}});
gg_list[22].push({num:77,level:5,sp_name:'Clouds',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [1, [4, "1"]]},fields:{}});
gg_list[22].push({num:78,level:5,sp_name:'Clouds',code:'motion_ifonedgebounce',one_hot:15,inputs:{},fields:{}});
gg_list[23]=[{num:79,level:5,sp_name:'Clouds2',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[23].push({num:80,level:5,sp_name:'Clouds2',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "RA#)]!xiuhdk?%-.|^wW"]},fields:{}});
gg_list[23].push({num:81,level:5,sp_name:'Clouds2',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [1, [4, "1"]]},fields:{}});
gg_list[23].push({num:82,level:5,sp_name:'Clouds2',code:'motion_ifonedgebounce',one_hot:15,inputs:{},fields:{}});
gg_list[24]=[{num:83,level:6,sp_name:'큰북',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD3", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[24].push({num:84,level:6,sp_name:'큰북',code:'sound_play',one_hot:41,inputs:{"SOUND_MENU": [1, "E8v`i%Tx2~U$$|AHb?_%"]},fields:{"SOUND_MENU": ["Drum Bass1", null]}});
gg_list[24].push({num:85,level:6,sp_name:'큰북',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "`greqC8}YJ[uVlYphXcp"]},fields:{"COSTUME": ["드럼_큰북", null]}});
gg_list[24].push({num:86,level:6,sp_name:'큰북',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "0.5"]]},fields:{}});
gg_list[24].push({num:87,level:6,sp_name:'큰북',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "-wgAgj?/PY+p=U-h#FU4"]},fields:{"COSTUME": ["드럼_큰북2", null]}});
gg_list[25]=[{num:88,level:6,sp_name:'작은북1',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[25].push({num:89,level:6,sp_name:'작은북1',code:'sound_play',one_hot:41,inputs:{"SOUND_MENU": [1, "veQ4-V{aFO*:YzYn/6x8"]},fields:{"SOUND_MENU": ["High Tom", null]}});
gg_list[25].push({num:90,level:6,sp_name:'작은북1',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "*A`@X1^aFT.#zNbfo#n!"]},fields:{"COSTUME": ["작은북1-1", null]}});
gg_list[25].push({num:91,level:6,sp_name:'작은북1',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "0.5"]]},fields:{}});
gg_list[25].push({num:92,level:6,sp_name:'작은북1',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "{:KFj;hvJkJ]`4]uKNm#"]},fields:{"COSTUME": ["작은북1-2", null]}});
gg_list[26]=[{num:93,level:6,sp_name:'작은북2',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD2", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[26].push({num:94,level:6,sp_name:'작은북2',code:'sound_play',one_hot:41,inputs:{"SOUND_MENU": [1, "{XQP[%M^l-wiFDtxQO}S"]},fields:{"SOUND_MENU": ["Tap Snare", null]}});
gg_list[26].push({num:95,level:6,sp_name:'작은북2',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "Pn.YhgYxz)}5-F}_~{7w"]},fields:{"COSTUME": ["작은북2-1", null]}});
gg_list[26].push({num:96,level:6,sp_name:'작은북2',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "0.5"]]},fields:{}});
gg_list[26].push({num:97,level:6,sp_name:'작은북2',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "m,pK|M=Nm3*jG()[c~H4"]},fields:{"COSTUME": ["작은북2-2", null]}});
gg_list[27]=[{num:98,level:6,sp_name:'심벌1',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "yL.c=7`nqRg8~(veKL_="]},fields:{"MOTIONSEL": ["7", null]}}];
gg_list[27].push({num:99,level:6,sp_name:'심벌1',code:'sound_play',one_hot:41,inputs:{"SOUND_MENU": [1, "*;WJ=[3xV*s,:!i`/^T1"]},fields:{"SOUND_MENU": ["Crash Cymbal", null]}});
gg_list[27].push({num:100,level:6,sp_name:'심벌1',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "e{x@seUbL3FNEk%fEv;U"]},fields:{"COSTUME": ["심벌1-1", null]}});
gg_list[27].push({num:101,level:6,sp_name:'심벌1',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "0.5"]]},fields:{}});
gg_list[27].push({num:102,level:6,sp_name:'심벌1',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "cB_L1;T.x9M,7qQk,x`1"]},fields:{"COSTUME": ["심벌1-2", null]}});
gg_list[28]=[{num:103,level:6,sp_name:'심벌2',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD4", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[28].push({num:104,level:6,sp_name:'심벌2',code:'sound_play',one_hot:41,inputs:{"SOUND_MENU": [1, "XuQGAE.G}~C.pU61iIo2"]},fields:{"SOUND_MENU": ["Hihat Cymbal", null]}});
gg_list[28].push({num:105,level:6,sp_name:'심벌2',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "p*{I;:63%.ZmyIN?7FI."]},fields:{"COSTUME": ["심벌2-1", null]}});
gg_list[28].push({num:106,level:6,sp_name:'심벌2',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "0.5"]]},fields:{}});
gg_list[28].push({num:107,level:6,sp_name:'심벌2',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "]wBKw!7iJMg9)1GWOr-@"]},fields:{"COSTUME": ["심벌2-2", null]}});
gg_list[29]=[{num:108,level:7,sp_name:'Bat',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[29].push({num:109,level:7,sp_name:'Bat',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "^![Nvt;,cVi5Qg,1VyJk"]},fields:{}});
gg_list[29].push({num:110,level:7,sp_name:'Bat',code:'control_if',one_hot:61,inputs:{"CONDITION": [2, "8jCb9IUg6p_}D${s6yme"], "SUBSTACK": [2, "w[ngJ{0.w~]ZDx2XU@)/"]},fields:{}});
gg_list[29].push({num:111,level:7,sp_name:'Bat',code:'operator_lt',one_hot:93,inputs:{"OPERAND1": [3, "-0zW+|yW:x($8s44ahKQ", [10, ""]], "OPERAND2": [1, [10, "50"]]},fields:{}});
gg_list[29].push({num:112,level:7,sp_name:'Bat',code:'probo_cube_illuminance',one_hot:118,inputs:{},fields:{}});
gg_list[29].push({num:113,level:7,sp_name:'Bat',code:'motion_glideto',one_hot:7,inputs:{"SECS": [1, [4, "1"]], "TO": [1, "M#]V(0WRiOB#Q)%R]E2v"]},fields:{"TO": ["_random_", null]}});
gg_list[30]=[{num:114,level:7,sp_name:'Bat',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[30].push({num:115,level:7,sp_name:'Bat',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "Ml#tx`_kxe|tbzwp1aMR"]},fields:{}});
gg_list[30].push({num:116,level:7,sp_name:'Bat',code:'control_if_else',one_hot:62,inputs:{"CONDITION": [2, "eM}E#A:14j1ks7H7(#Z3"], "SUBSTACK": [2, "Yu3*4K=Hu!DLS]{Kvvu3"], "SUBSTACK2": [2, "zcq]C[qUUV[g;9DRSEcP"]},fields:{}});
gg_list[30].push({num:117,level:7,sp_name:'Bat',code:'operator_lt',one_hot:93,inputs:{"OPERAND1": [3, "`9ffb{5%D?~wmTb3UM^x", [10, ""]], "OPERAND2": [1, [10, "50"]]},fields:{}});
gg_list[30].push({num:118,level:7,sp_name:'Bat',code:'probo_cube_illuminance',one_hot:118,inputs:{},fields:{}});
gg_list[30].push({num:119,level:7,sp_name:'Bat',code:'motion_pointindirection',one_hot:9,inputs:{"DIRECTION": [1, [8, "90"]]},fields:{}});
gg_list[30].push({num:120,level:7,sp_name:'Bat',code:'looks_nextcostume',one_hot:25,inputs:{},fields:{}});
gg_list[30].push({num:121,level:7,sp_name:'Bat',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "0.1"]]},fields:{}});
gg_list[30].push({num:122,level:7,sp_name:'Bat',code:'motion_pointindirection',one_hot:9,inputs:{"DIRECTION": [1, [8, "-90"]]},fields:{}});
gg_list[30].push({num:123,level:7,sp_name:'Bat',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "R^Bl|FIS7n:bg[hJG7FE"]},fields:{"COSTUME": ["bat-d", null]}});
gg_list[30].push({num:124,level:7,sp_name:'Bat',code:'motion_gotoxy',one_hot:6,inputs:{"X": [1, [4, "73"]], "Y": [1, [4, "49"]]},fields:{}});
gg_list[31]=[{num:125,level:8,sp_name:'오르골',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[31].push({num:126,level:8,sp_name:'오르골',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "@!2|M2;AwvNt3*lrmpL*"]},fields:{}});
gg_list[31].push({num:127,level:8,sp_name:'오르골',code:'control_if',one_hot:61,inputs:{"CONDITION": [2, "mM?vO`vnTw[S~l%O-AIM"], "SUBSTACK": [2, "TN^z,Sn3ZI{M9!5g-jpn"]},fields:{}});
gg_list[31].push({num:128,level:8,sp_name:'오르골',code:'operator_gt',one_hot:92,inputs:{"OPERAND1": [3, "KD;;:v2RCi%cE#]kCnDy", [10, ""]], "OPERAND2": [1, [10, "50"]]},fields:{}});
gg_list[31].push({num:129,level:8,sp_name:'오르골',code:'probo_cube_illuminance',one_hot:118,inputs:{},fields:{}});
gg_list[31].push({num:130,level:8,sp_name:'오르골',code:'probo_cube_mellody_playtoend',one_hot:126,inputs:{},fields:{"PRO_CUBE_MELODY": ["7", null]}});
gg_list[32]=[{num:131,level:8,sp_name:'오르골',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[32].push({num:132,level:8,sp_name:'오르골',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "S9iT{V{;Kz^$vNYqj_eu"]},fields:{}});
gg_list[32].push({num:133,level:8,sp_name:'오르골',code:'control_if',one_hot:61,inputs:{"CONDITION": [2, "oN[gXcgx8uQ|B*m3(SSc"], "SUBSTACK": [2, "O~ZO[cNCG{^|V*1{{CQ]"]},fields:{}});
gg_list[32].push({num:134,level:8,sp_name:'오르골',code:'operator_lt',one_hot:93,inputs:{"OPERAND1": [3, "ADScv(-XUPFzX_JbYC^x", [10, ""]], "OPERAND2": [1, [10, "50"]]},fields:{}});
gg_list[32].push({num:135,level:8,sp_name:'오르골',code:'probo_cube_illuminance',one_hot:118,inputs:{},fields:{}});
gg_list[32].push({num:136,level:8,sp_name:'오르골',code:'probo_cube_sound_stop',one_hot:129,inputs:{},fields:{}});
gg_list[33]=[{num:137,level:8,sp_name:'오르골',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[33].push({num:138,level:8,sp_name:'오르골',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "aT~3W|,~$N=mZmImvpvX"]},fields:{}});
gg_list[33].push({num:139,level:8,sp_name:'오르골',code:'control_if_else',one_hot:62,inputs:{"CONDITION": [2, "c=:a;rn}zrhX4qAo_5_M"], "SUBSTACK": [2, "[AItCUrZl+^kl.0~z_+t"], "SUBSTACK2": [2, "[H_uHj}3nNWATp_=j;~w"]},fields:{}});
gg_list[33].push({num:140,level:8,sp_name:'오르골',code:'operator_gt',one_hot:92,inputs:{"OPERAND1": [3, "TR6$-i[Vr`A2t}=(qP-|", [10, ""]], "OPERAND2": [1, [10, "50"]]},fields:{}});
gg_list[33].push({num:141,level:8,sp_name:'오르골',code:'probo_cube_illuminance',one_hot:118,inputs:{},fields:{}});
gg_list[33].push({num:142,level:8,sp_name:'오르골',code:'probo_cube_selecter',one_hot:120,inputs:{"CUBE_LED_IDX": [1, "xZ8pQ!_63K+R.#r=A4_E"], "CUBE_SPEEDS": [1, "5acVG*]fjMUp]9:t[.$|"]},fields:{"CUBE_SPEEDS": ["0", null],"SELECTER": ["24", null]}});
gg_list[33].push({num:143,level:8,sp_name:'오르골',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "1"]]},fields:{}});
gg_list[33].push({num:144,level:8,sp_name:'오르골',code:'probo_cube_selecter',one_hot:120,inputs:{"CUBE_LED_IDX": [1, "xHi2PczT!MPb#.Ni*wr~"], "CUBE_SPEEDS": [1, "C73^b4aQ=Vt%N,8hrrqt"]},fields:{"CUBE_SPEEDS": ["0", null],"SELECTER": ["25", null]}});
gg_list[33].push({num:145,level:8,sp_name:'오르골',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "1"]]},fields:{}});
gg_list[33].push({num:146,level:8,sp_name:'오르골',code:'probo_cube_selecter',one_hot:120,inputs:{"CUBE_LED_IDX": [1, "1VKonJ[/fo|8e@IK{IEV"], "CUBE_SPEEDS": [1, "dJjy^tu[cg_p;/4}6W^|"]},fields:{"CUBE_SPEEDS": ["0", null],"SELECTER": ["19", null]}});
gg_list[33].push({num:147,level:8,sp_name:'오르골',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "1"]]},fields:{}});
gg_list[33].push({num:148,level:8,sp_name:'오르골',code:'probo_cube_clear',one_hot:123,inputs:{},fields:{}});
gg_list[34]=[{num:149,level:8,sp_name:'어린왕자',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[34].push({num:150,level:8,sp_name:'어린왕자',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "i~T73PfuLxp}^.?/[Ckq"]},fields:{}});
gg_list[34].push({num:151,level:8,sp_name:'어린왕자',code:'control_if',one_hot:61,inputs:{"CONDITION": [2, "3T-9[^W@GsVM(um7|@b^"], "SUBSTACK": [2, "%w]y|^,rq[*iQgn/k6!O"]},fields:{}});
gg_list[34].push({num:152,level:8,sp_name:'어린왕자',code:'operator_gt',one_hot:92,inputs:{"OPERAND1": [3, "l1:64y;vpYb?O2Q~=#C-", [10, ""]], "OPERAND2": [1, [10, "50"]]},fields:{}});
gg_list[34].push({num:153,level:8,sp_name:'어린왕자',code:'probo_cube_illuminance',one_hot:118,inputs:{},fields:{}});
gg_list[34].push({num:154,level:8,sp_name:'어린왕자',code:'motion_turnright',one_hot:3,inputs:{"DEGREES": [1, [4, "1"]]},fields:{}});
gg_list[35]=[{num:155,level:9,sp_name:'달리는 소녀',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "k+Ha^Hf5|/}TBreo7|b|"]},fields:{"MOTIONSEL": ["7", null]}}];
gg_list[35].push({num:156,level:9,sp_name:'달리는 소녀',code:'looks_nextcostume',one_hot:25,inputs:{},fields:{}});
gg_list[35].push({num:157,level:9,sp_name:'달리는 소녀',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [1, [4, "1"]]},fields:{}});
gg_list[35].push({num:158,level:9,sp_name:'달리는 소녀',code:'sound_play',one_hot:41,inputs:{"SOUND_MENU": [1, "S1*]tKs5k2R8VrbrGF+p"]},fields:{"SOUND_MENU": ["Finger Snap", null]}});
gg_list[36]=[{num:159,level:9,sp_name:'달리는 소녀',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[36].push({num:160,level:9,sp_name:'달리는 소녀',code:'motion_gotoxy',one_hot:6,inputs:{"X": [1, [4, "-204"]], "Y": [1, [4, "-27"]]},fields:{}});
gg_list[37]=[{num:161,level:9,sp_name:'결승선',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[37].push({num:162,level:9,sp_name:'결승선',code:'sound_play',one_hot:41,inputs:{"SOUND_MENU": [1, "NT0OxBVZ{!S!ONREztcH"]},fields:{"SOUND_MENU": ["총소리", null]}});
gg_list[37].push({num:163,level:9,sp_name:'결승선',code:'sensing_resettimer',one_hot:82,inputs:{},fields:{}});
gg_list[37].push({num:164,level:9,sp_name:'결승선',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [2, "v(y.!T.@pW[Bt/4u{^;d"]},fields:{}});
gg_list[37].push({num:165,level:9,sp_name:'결승선',code:'sensing_touchingobject',one_hot:69,inputs:{"TOUCHINGOBJECTMENU": [1, "v{B[iEB+qc0{zMJfg~)m"]},fields:{"TOUCHINGOBJECTMENU": ["달리는 소녀", null]}});
gg_list[37].push({num:166,level:9,sp_name:'결승선',code:'looks_say',one_hot:21,inputs:{"MESSAGE": [3, "cb:O{RaYB+NDA];jbf/R", [10, "\uc548\ub155!"]]},fields:{}});
gg_list[37].push({num:167,level:9,sp_name:'결승선',code:'sensing_timer',one_hot:81,inputs:{},fields:{}});
gg_list[37].push({num:168,level:9,sp_name:'결승선',code:'sound_play',one_hot:41,inputs:{"SOUND_MENU": [1, "/n?2r0]`g0GGB(iVTBe_"]},fields:{"SOUND_MENU": ["Goal Cheer", null]}});
gg_list[38]=[{num:169,level:10,sp_name:'비행기',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "X5kYy.@C{c4=kN@/`kNm"]},fields:{"MOTIONSEL": ["2", null]}}];
gg_list[38].push({num:170,level:10,sp_name:'비행기',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "3kMzzTnVDGUjjEZv2t~4"]},fields:{"COSTUME": ["왼쪽회전", null]}});
gg_list[38].push({num:171,level:10,sp_name:'비행기',code:'motion_changexby',one_hot:11,inputs:{"DX": [1, [4, "-5"]]},fields:{}});
gg_list[39]=[{num:172,level:10,sp_name:'비행기',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "qt1lJ}0MhjHdavucEp3a"]},fields:{"MOTIONSEL": ["6", null]}}];
gg_list[39].push({num:173,level:10,sp_name:'비행기',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "g@N#v!p.VR7J+t{Y1PtL"]},fields:{"COSTUME": ["정면", null]}});
gg_list[40]=[{num:174,level:10,sp_name:'비행기',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "GK[8t2~@*(~i|uSk-Y/b"]},fields:{"MOTIONSEL": ["3", null]}}];
gg_list[40].push({num:175,level:10,sp_name:'비행기',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "Z2m3bHW%eG8!?JYY/uu8"]},fields:{"COSTUME": ["오른쪽회전", null]}});
gg_list[40].push({num:176,level:10,sp_name:'비행기',code:'motion_changexby',one_hot:11,inputs:{"DX": [1, [4, "5"]]},fields:{}});
gg_list[41]=[{num:177,level:10,sp_name:'돌맹이',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[41].push({num:178,level:10,sp_name:'돌맹이',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "lKGS;ls96R{*N8hyUi=B"]},fields:{"COSTUME": ["돌맹이", null]}});
gg_list[41].push({num:179,level:10,sp_name:'돌맹이',code:'motion_gotoxy',one_hot:6,inputs:{"X": [3, "M:v]G/nmYR7Tak@a1@}#", [4, "-48"]], "Y": [1, [4, "150"]]},fields:{}});
gg_list[41].push({num:180,level:10,sp_name:'돌맹이',code:'operator_random',one_hot:91,inputs:{"FROM": [1, [4, "-200"]], "TO": [1, [4, "200"]]},fields:{}});
gg_list[41].push({num:181,level:10,sp_name:'돌맹이',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "XY){1uod%c{#Di~_IIp3"]},fields:{}});
gg_list[41].push({num:182,level:10,sp_name:'돌맹이',code:'motion_changeyby',one_hot:13,inputs:{"DY": [1, [4, "-5"]]},fields:{}});
gg_list[41].push({num:183,level:10,sp_name:'돌맹이',code:'control_if',one_hot:61,inputs:{"CONDITION": [2, "QZL4A!yI2*A#QP4rjWED"], "SUBSTACK": [2, "}n+##As01[:4.4rVA#QP"]},fields:{}});
gg_list[41].push({num:184,level:10,sp_name:'돌맹이',code:'sensing_touchingobject',one_hot:69,inputs:{"TOUCHINGOBJECTMENU": [1, ",p2gHH]j9%#(]?_6/`av"]},fields:{"TOUCHINGOBJECTMENU": ["_edge_", null]}});
gg_list[41].push({num:185,level:10,sp_name:'돌맹이',code:'motion_gotoxy',one_hot:6,inputs:{"X": [3, "b-eO2t[%QnqG^Y@1FW_#", [4, "-48"]], "Y": [1, [4, "150"]]},fields:{}});
gg_list[41].push({num:186,level:10,sp_name:'돌맹이',code:'operator_random',one_hot:91,inputs:{"FROM": [1, [4, "-240"]], "TO": [1, [4, "240"]]},fields:{}});
gg_list[41].push({num:187,level:10,sp_name:'돌맹이',code:'control_if',one_hot:61,inputs:{"CONDITION": [2, "zF]J[%AVX,#NxrJv9=8Y"], "SUBSTACK": [2, "qOn[6/C{3c5~.4;0]kjM"]},fields:{}});
gg_list[41].push({num:188,level:10,sp_name:'돌맹이',code:'sensing_touchingobject',one_hot:69,inputs:{"TOUCHINGOBJECTMENU": [1, "^9GlUgzK{Vbn]ZTj:n-^"]},fields:{"TOUCHINGOBJECTMENU": ["비행기", null]}});
gg_list[41].push({num:189,level:10,sp_name:'돌맹이',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "ph=6QOq|Yzv#O#wF5cjM"]},fields:{"COSTUME": ["게임오버", null]}});
gg_list[41].push({num:190,level:10,sp_name:'돌맹이',code:'control_stop',one_hot:65,inputs:{},fields:{"STOP_OPTION": ["all", null]}});
gg_list[42]=[{num:191,level:10,sp_name:'돌맹이2',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[42].push({num:192,level:10,sp_name:'돌맹이2',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "X}!g8O.1l`,OC^np(otW"]},fields:{"COSTUME": ["돌맹이"]}});
gg_list[42].push({num:193,level:10,sp_name:'돌맹이2',code:'motion_gotoxy',one_hot:6,inputs:{"X": [3, "f,Lnj`rkQHKu3zf.a~0+", [4, "-48"]], "Y": [1, [4, "150"]]},fields:{}});
gg_list[42].push({num:194,level:10,sp_name:'돌맹이2',code:'operator_random',one_hot:91,inputs:{"FROM": [1, [4, "-200"]], "TO": [1, [4, "200"]]},fields:{}});
gg_list[42].push({num:195,level:10,sp_name:'돌맹이2',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [3, "#!oO#tAk_(K1?WZ#x!|a", null]},fields:{}});
gg_list[42].push({num:196,level:10,sp_name:'돌맹이2',code:'motion_changeyby',one_hot:13,inputs:{"DY": [1, [4, "-8"]]},fields:{}});
gg_list[42].push({num:197,level:10,sp_name:'돌맹이2',code:'control_if',one_hot:61,inputs:{"CONDITION": [3, ":8=D:2Aburd;qkTsIw7j", null], "SUBSTACK": [3, "j86,5%UWL(V8pq^1,Ln0", null]},fields:{}});
gg_list[42].push({num:198,level:10,sp_name:'돌맹이2',code:'sensing_touchingobject',one_hot:69,inputs:{"TOUCHINGOBJECTMENU": [1, "Sk2r*B~cf(QGA#xlwCP)"]},fields:{"TOUCHINGOBJECTMENU": ["_edge_", null]}});
gg_list[42].push({num:199,level:10,sp_name:'돌맹이2',code:'motion_gotoxy',one_hot:6,inputs:{"X": [3, ".XWWjQ[S@bnUw;}njG%]", [4, "-48"]], "Y": [1, [4, "150"]]},fields:{}});
gg_list[42].push({num:200,level:10,sp_name:'돌맹이2',code:'operator_random',one_hot:91,inputs:{"FROM": [1, [4, "-240"]], "TO": [1, [4, "240"]]},fields:{}});
gg_list[42].push({num:201,level:10,sp_name:'돌맹이2',code:'control_if',one_hot:61,inputs:{"CONDITION": [3, "Oex6t]=)=J*8S~gr?d[P", null], "SUBSTACK": [3, "AM5tXUBLOYREdPDRJZeJ", null]},fields:{}});
gg_list[42].push({num:202,level:10,sp_name:'돌맹이2',code:'sensing_touchingobject',one_hot:69,inputs:{"TOUCHINGOBJECTMENU": [1, "0z_6S!b*6+OSFR:!ApJH"]},fields:{"TOUCHINGOBJECTMENU": ["비행기", null]}});
gg_list[42].push({num:203,level:10,sp_name:'돌맹이2',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "?=noca|G}XK?f2E[0!?l"]},fields:{"COSTUME": ["게임오버"]}});
gg_list[42].push({num:204,level:10,sp_name:'돌맹이2',code:'control_stop',one_hot:65,inputs:{},fields:{"STOP_OPTION": ["all", null]}});
gg_list[43]=[{num:205,level:10,sp_name:'돌맹이3',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[43].push({num:206,level:10,sp_name:'돌맹이3',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, ")2Wa#bstYyYYjK:iDOmn"]},fields:{"COSTUME": ["돌맹이"]}});
gg_list[43].push({num:207,level:10,sp_name:'돌맹이3',code:'motion_gotoxy',one_hot:6,inputs:{"X": [3, "}:Meiinq_6I%o:4DzEMb", [4, "-48"]], "Y": [1, [4, "150"]]},fields:{}});
gg_list[43].push({num:208,level:10,sp_name:'돌맹이3',code:'operator_random',one_hot:91,inputs:{"FROM": [1, [4, "-200"]], "TO": [1, [4, "200"]]},fields:{}});
gg_list[43].push({num:209,level:10,sp_name:'돌맹이3',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [3, "O.B+ya~![=DnEB)jtU=E", null]},fields:{}});
gg_list[43].push({num:210,level:10,sp_name:'돌맹이3',code:'motion_changeyby',one_hot:13,inputs:{"DY": [1, [4, "-4"]]},fields:{}});
gg_list[43].push({num:211,level:10,sp_name:'돌맹이3',code:'control_if',one_hot:61,inputs:{"CONDITION": [3, "X?iN*a:0z#%Y-Zm!PEMp", null], "SUBSTACK": [3, "kSRn176k+R.etkGG]EOF", null]},fields:{}});
gg_list[43].push({num:212,level:10,sp_name:'돌맹이3',code:'sensing_touchingobject',one_hot:69,inputs:{"TOUCHINGOBJECTMENU": [1, "sQqJry-ApJ/=W~GICUSy"]},fields:{"TOUCHINGOBJECTMENU": ["_edge_", null]}});
gg_list[43].push({num:213,level:10,sp_name:'돌맹이3',code:'motion_gotoxy',one_hot:6,inputs:{"X": [3, "ZdpTFU,v{n2?=uZ|3D!g", [4, "-48"]], "Y": [1, [4, "150"]]},fields:{}});
gg_list[43].push({num:214,level:10,sp_name:'돌맹이3',code:'operator_random',one_hot:91,inputs:{"FROM": [1, [4, "-240"]], "TO": [1, [4, "240"]]},fields:{}});
gg_list[43].push({num:215,level:10,sp_name:'돌맹이3',code:'control_if',one_hot:61,inputs:{"CONDITION": [3, "AW)Ar/LwG^I(KBHW~+W0", null], "SUBSTACK": [3, "Ve?1Y:U}Is~QW-nk_umB", null]},fields:{}});
gg_list[43].push({num:216,level:10,sp_name:'돌맹이3',code:'sensing_touchingobject',one_hot:69,inputs:{"TOUCHINGOBJECTMENU": [1, "NmI@=TOsJruCm-SFgh@0"]},fields:{"TOUCHINGOBJECTMENU": ["비행기", null]}});
gg_list[43].push({num:217,level:10,sp_name:'돌맹이3',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "X:zdaRaLf!Ma.B6+Uh|d"]},fields:{"COSTUME": ["게임오버"]}});
gg_list[43].push({num:218,level:10,sp_name:'돌맹이3',code:'control_stop',one_hot:65,inputs:{},fields:{"STOP_OPTION": ["all", null]}});
gg_list[44]=[{num:219,level:11,sp_name:'권투소년',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "jn0`[TW=@:yK.t~?V:%k"]},fields:{"MOTIONSEL": ["7", null]}}];
gg_list[44].push({num:220,level:11,sp_name:'권투소년',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "TZoNWGC+b]R~@y|Nx*q?"]},fields:{"COSTUME": ["권투소년2", null]}});
gg_list[44].push({num:221,level:11,sp_name:'권투소년',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "0.1"]]},fields:{}});
gg_list[44].push({num:222,level:11,sp_name:'권투소년',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "z#a9Hm`U.[Y,kPvf-h;d"]},fields:{"COSTUME": ["권투소년1", null]}});
gg_list[45]=[{num:223,level:11,sp_name:'샌드백',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[45].push({num:224,level:11,sp_name:'샌드백',code:'sensing_resettimer',one_hot:82,inputs:{},fields:{}});
gg_list[45].push({num:225,level:11,sp_name:'샌드백',code:'data_setvariableto',one_hot:106,inputs:{"VALUE": [1, [10, "0"]]},fields:{"VARIABLE": ["타격", "UFGxofJHkB6G@vJ8m=Z]"]}});
gg_list[45].push({num:226,level:11,sp_name:'샌드백',code:'control_forever',one_hot:59,inputs:{"SUBSTACK": [2, "btN9,-a*04zWIo%t^FE$"]},fields:{}});
gg_list[45].push({num:227,level:11,sp_name:'샌드백',code:'control_if',one_hot:61,inputs:{"CONDITION": [2, "sf{4)m(/7fQOVj^~@.I_"], "SUBSTACK": [2, "/=eEB[Ow9m3m+nS;@1V~"]},fields:{}});
gg_list[45].push({num:228,level:11,sp_name:'샌드백',code:'operator_gt',one_hot:92,inputs:{"OPERAND1": [3, "4c#5UA+sRjbRyBS!Rzh@", [10, ""]], "OPERAND2": [1, [10, "8"]]},fields:{}});
gg_list[45].push({num:229,level:11,sp_name:'샌드백',code:'probo_cube_acceleration',one_hot:117,inputs:{},fields:{"PRO_CUBE_AXIS_ANALOG": ["L", null]}});
gg_list[45].push({num:230,level:11,sp_name:'샌드백',code:'data_changevariableby',one_hot:107,inputs:{"VALUE": [1, [4, "1"]]},fields:{"VARIABLE": ["타격", "UFGxofJHkB6G@vJ8m=Z]"]}});
gg_list[45].push({num:231,level:11,sp_name:'샌드백',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "0.4"]]},fields:{}});
gg_list[45].push({num:232,level:11,sp_name:'샌드백',code:'control_if',one_hot:61,inputs:{"CONDITION": [2, "s^7d6%jhtl$0pWApTMUz"], "SUBSTACK": [2, "If2U,Q-Qw%f8d4o{^:f)"]},fields:{}});
gg_list[45].push({num:233,level:11,sp_name:'샌드백',code:'operator_gt',one_hot:92,inputs:{"OPERAND1": [3, "ktDq!J}T:){5gn#Qcx.#", [10, ""]], "OPERAND2": [1, [10, "30"]]},fields:{}});
gg_list[45].push({num:234,level:11,sp_name:'샌드백',code:'sensing_timer',one_hot:81,inputs:{},fields:{}});
gg_list[45].push({num:235,level:11,sp_name:'샌드백',code:'control_stop',one_hot:65,inputs:{},fields:{"STOP_OPTION": ["all", null]}});
gg_list[46]=[{num:236,level:11,sp_name:'샌드백',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "7,sHnZJtJb%^3[rlQ7-="]},fields:{"MOTIONSEL": ["7", null]}}];
gg_list[46].push({num:237,level:11,sp_name:'샌드백',code:'sound_play',one_hot:41,inputs:{"SOUND_MENU": [1, "{u@r10G*c7n!HS#B)3Gl"]},fields:{"SOUND_MENU": ["Crunch", null]}});
gg_list[46].push({num:238,level:11,sp_name:'샌드백',code:'control_repeat',one_hot:58,inputs:{"TIMES": [1, [6, "4"]], "SUBSTACK": [2, "Qw)c`@8PRcl8E@F?E5b="]},fields:{}});
gg_list[46].push({num:239,level:11,sp_name:'샌드백',code:'looks_nextcostume',one_hot:25,inputs:{},fields:{}});
gg_list[46].push({num:240,level:11,sp_name:'샌드백',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "0.1"]]},fields:{}});
gg_list[47]=[{num:241,level:13,sp_name:'Cat',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[47].push({num:242,level:13,sp_name:'Cat',code:'probo_cube_selecter',one_hot:120,inputs:{"CUBE_LED_IDX": [1, "oV)vLt1s=tRV8$0z-e:i"], "CUBE_SPEEDS": [1, "!g$g3=+rrYZrbpQsvv)="]},fields:{"CUBE_SPEEDS": ["0", null],"SELECTER": ["0", null]}});
gg_list[47].push({num:243,level:13,sp_name:'Cat',code:'probo_cube_picker',one_hot:121,inputs:{"CUBE_LED_DATA": [1, "UTwc*^ywq^TrkL#J=%7S"], "CUBE_SPEEDS": [1, "=;XWzYI3%q]+5;}X~@E0"]},fields:{"CUBE_SPEEDS": ["0", null],"PICKER": ["0000000000000000000000000000", null]}});
gg_list[47].push({num:244,level:13,sp_name:'Cat',code:'probo_cube_text',one_hot:122,inputs:{"CUBE_LED_TEXT": [1, [10, "Hello"]], "CUBE_SPEEDS": [1, "fQ(8[ZzAG]zp0Y~l-}hF"]},fields:{"CUBE_SPEEDS": ["1", null]}});
gg_list[47].push({num:245,level:13,sp_name:'Cat',code:'probo_cube_pixel',one_hot:124,inputs:{"PIXELX": [1, [4, " 0 "]], "PIXELY": [1, [4, " 0 "]], "PRO_ONOFF": [1, ".]my+m2/,(AX,+8nAa]G"]},fields:{"PRO_ONOFF": ["0", null]}});
gg_list[47].push({num:246,level:13,sp_name:'Cat',code:'probo_cube_mellody_play',one_hot:125,inputs:{},fields:{"PRO_CUBE_MELODY": ["1", null]}});
gg_list[47].push({num:247,level:13,sp_name:'Cat',code:'probo_cube_mellody_playtoend',one_hot:126,inputs:{},fields:{"PRO_CUBE_MELODY": ["1", null]}});
gg_list[48]=[{num:248,level:13,sp_name:'Cat',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[48].push({num:249,level:13,sp_name:'Cat',code:'motion_goto',one_hot:5,inputs:{"TO": [1, "iWx#9n)O662Kc8}/d]KM"]},fields:{"TO": ["_random_", null]}});
gg_list[48].push({num:250,level:13,sp_name:'Cat',code:'motion_glideto',one_hot:7,inputs:{"SECS": [1, [4, "1"]], "TO": [1, "GRx]Wu|qJ^0s?em6R.nP"]},fields:{"TO": ["_random_", null]}});
gg_list[48].push({num:251,level:13,sp_name:'Cat',code:'motion_pointtowards',one_hot:10,inputs:{"TOWARDS": [1, "l]gb4cOa|G47{8],Sz;?"]},fields:{"TOWARDS": ["_mouse_", null]}});
gg_list[48].push({num:252,level:13,sp_name:'Cat',code:'motion_setrotationstyle',one_hot:16,inputs:{},fields:{"STYLE": ["left-right", null]}});
gg_list[49]=[{num:253,level:13,sp_name:'Cat',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[49].push({num:254,level:13,sp_name:'Cat',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "uIqlRE3pg3xHwdMnYGb."]},fields:{"COSTUME": ["cat-a", null]}});
gg_list[49].push({num:255,level:13,sp_name:'Cat',code:'looks_switchbackdropto',one_hot:26,inputs:{"BACKDROP": [1, "*=;hv;DHtSM{+N+NH%Di"]},fields:{"BACKDROP": ["배경 1", null]}});
gg_list[49].push({num:256,level:13,sp_name:'Cat',code:'looks_changeeffectby',one_hot:30,inputs:{"CHANGE": [3, "u![v8[!-{jda?c_%eWZj", [4, "25"]]},fields:{"EFFECT": ["COLOR", null]}});
gg_list[49].push({num:257,level:13,sp_name:'Cat',code:'looks_costumenumbername',one_hot:37,inputs:{},fields:{"NUMBER_NAME": ["number", null]}});
gg_list[49].push({num:258,level:13,sp_name:'Cat',code:'looks_seteffectto',one_hot:31,inputs:{"VALUE": [3, "Uj@?%P@@v.K|r$|bwwz}", [4, "0"]]},fields:{"EFFECT": ["COLOR", null]}});
gg_list[49].push({num:259,level:13,sp_name:'Cat',code:'looks_backdropnumbername',one_hot:38,inputs:{},fields:{"NUMBER_NAME": ["number", null]}});
gg_list[49].push({num:260,level:13,sp_name:'Cat',code:'looks_gotofrontback',one_hot:35,inputs:{},fields:{"FRONT_BACK": ["front", null]}});
gg_list[49].push({num:261,level:13,sp_name:'Cat',code:'looks_goforwardbackwardlayers',one_hot:36,inputs:{"NUM": [1, [7, "1"]]},fields:{"FORWARD_BACKWARD": ["forward", null]}});
gg_list[50]=[{num:262,level:13,sp_name:'Cat',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[50].push({num:263,level:13,sp_name:'Cat',code:'sound_playuntildone',one_hot:40,inputs:{"SOUND_MENU": [1, "%(bStwLc=DBt~6#L4?@6"]},fields:{"SOUND_MENU": ["Meow", null]}});
gg_list[50].push({num:264,level:13,sp_name:'Cat',code:'sound_play',one_hot:41,inputs:{"SOUND_MENU": [1, "dJ+78Cc]{r/c9*CgF_Vl"]},fields:{"SOUND_MENU": ["Meow", null]}});
gg_list[50].push({num:265,level:13,sp_name:'Cat',code:'sound_changeeffectby',one_hot:43,inputs:{"VALUE": [1, [4, "10"]]},fields:{"EFFECT": ["PITCH", null]}});
gg_list[50].push({num:266,level:13,sp_name:'Cat',code:'sound_seteffectto',one_hot:44,inputs:{"VALUE": [1, [4, "100"]]},fields:{"EFFECT": ["PITCH", null]}});
gg_list[51]=[{num:267,level:13,sp_name:'Cat',code:'event_whenbackdropswitchesto',one_hot:52,inputs:{},fields:{"BACKDROP": ["배경 1", null]}}];
gg_list[51].push({num:268,level:13,sp_name:'Cat',code:'event_broadcast',one_hot:55,inputs:{"BROADCAST_INPUT": [1, [11, "\uba54\uc2dc\uc9c01", "dFre=f3p7Py0(T[S+)NN"]]},fields:{}});
gg_list[51].push({num:269,level:13,sp_name:'Cat',code:'event_broadcastandwait',one_hot:56,inputs:{"BROADCAST_INPUT": [1, [11, "\uba54\uc2dc\uc9c01", "dFre=f3p7Py0(T[S+)NN"]]},fields:{}});
gg_list[52]=[{num:270,level:13,sp_name:'Cat',code:'event_whengreaterthan',one_hot:53,inputs:{"VALUE": [1, [4, "10"]]},fields:{"WHENGREATERTHANMENU": ["LOUDNESS", null]}}];
gg_list[52].push({num:271,level:13,sp_name:'Cat',code:'control_create_clone_of',one_hot:67,inputs:{"CLONE_OPTION": [1, "n:2@QDt|w^ODU*OQfw4`"]},fields:{"CLONE_OPTION": ["_myself_", null]}});
gg_list[52].push({num:272,level:13,sp_name:'Cat',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [2, "iYl+,_UkEAUt%?-Fd9uW"]},fields:{}});
gg_list[52].push({num:273,level:13,sp_name:'Cat',code:'sensing_touchingobject',one_hot:69,inputs:{"TOUCHINGOBJECTMENU": [1, "9bx^h-?)4reQZ.C~G{8h"]},fields:{"TOUCHINGOBJECTMENU": ["_mouse_", null]}});
gg_list[52].push({num:274,level:13,sp_name:'Cat',code:'sensing_askandwait',one_hot:73,inputs:{"QUESTION": [3, "U]EX2BpjHO+k]guy%X)[", [10, "What's your name?"]]},fields:{}});
gg_list[52].push({num:275,level:13,sp_name:'Cat',code:'sensing_distanceto',one_hot:72,inputs:{"DISTANCETOMENU": [1, "F]B9(K:i)mRbUj!#hvc-"]},fields:{"DISTANCETOMENU": ["_mouse_", null]}});
gg_list[52].push({num:276,level:13,sp_name:'Cat',code:'sensing_setdragmode',one_hot:79,inputs:{},fields:{"DRAG_MODE": ["draggable", null]}});
gg_list[53]=[{num:277,level:13,sp_name:'Cat',code:'event_whenbackdropswitchesto',one_hot:52,inputs:{},fields:{"BACKDROP": ["배경 1", null]}}];
gg_list[53].push({num:278,level:13,sp_name:'Cat',code:'looks_say',one_hot:21,inputs:{"MESSAGE": [3, ";U:-9pqlz@VbM93]g2#+", [10, "\uc548\ub155!"]]},fields:{}});
gg_list[53].push({num:279,level:13,sp_name:'Cat',code:'sensing_of',one_hot:83,inputs:{"OBJECT": [1, ".},XW5)nV{L;tLd!X4A7"]},fields:{"PROPERTY": ["backdrop #", null],"OBJECT": ["_stage_", null]}});
gg_list[53].push({num:280,level:13,sp_name:'Cat',code:'looks_think',one_hot:23,inputs:{"MESSAGE": [3, "Tfis/)_$x5v/`W+,Q-==", [10, "\uc74c..."]]},fields:{}});
gg_list[53].push({num:281,level:13,sp_name:'Cat',code:'sensing_dayssince2000',one_hot:85,inputs:{},fields:{}});
gg_list[53].push({num:282,level:13,sp_name:'Cat',code:'looks_say',one_hot:21,inputs:{"MESSAGE": [3, "t3xJzIiW4Zi8nbL|(w(4", [10, "\uc548\ub155!"]]},fields:{}});
gg_list[53].push({num:283,level:13,sp_name:'Cat',code:'sensing_current',one_hot:84,inputs:{},fields:{"CURRENTMENU": ["YEAR", null]}});
gg_list[53].push({num:284,level:13,sp_name:'Cat',code:'looks_say',one_hot:21,inputs:{"MESSAGE": [3, "5u|*|WL=KIefkJg%=K[#", [10, "\uc548\ub155!"]]},fields:{}});
gg_list[53].push({num:285,level:13,sp_name:'Cat',code:'operator_mathop',one_hot:104,inputs:{"NUM": [1, [4, "77"]]},fields:{"OPERATOR": ["abs", null]}});
gg_list[54]=[{num:286,level:13,sp_name:'Cat',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[54].push({num:287,level:13,sp_name:'Cat',code:'data_setvariableto',one_hot:106,inputs:{"VALUE": [1, [10, "0"]]},fields:{"VARIABLE": ["나의 변수", "`jEk@4|i[#Fk?(8x)AV.-my variable"]}});
gg_list[54].push({num:288,level:13,sp_name:'Cat',code:'data_changevariableby',one_hot:107,inputs:{"VALUE": [1, [4, "1"]]},fields:{"VARIABLE": ["나의 변수", "`jEk@4|i[#Fk?(8x)AV.-my variable"]}});
gg_list[54].push({num:289,level:13,sp_name:'Cat',code:'data_showvariable',one_hot:108,inputs:{},fields:{"VARIABLE": ["나의 변수", "`jEk@4|i[#Fk?(8x)AV.-my variable"]}});
gg_list[54].push({num:290,level:13,sp_name:'Cat',code:'data_hidevariable',one_hot:109,inputs:{},fields:{"VARIABLE": ["나의 변수", "`jEk@4|i[#Fk?(8x)AV.-my variable"]}});
gg_list[55]=[{num:291,level:13,sp_name:'Cat',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[55].push({num:292,level:13,sp_name:'Cat',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [3, "s8t;%foO8BLmobaqT5Qz", [4, "10"]]},fields:{}});
gg_list[55].push({num:293,level:13,sp_name:'Cat',code:'probo_cube_btn_analog',one_hot:116,inputs:{},fields:{"PRO_CUBE_SWITCH_ANALOG": ["SA1", null]}});
gg_list[55].push({num:294,level:13,sp_name:'Cat',code:'motion_backmovesteps',one_hot:2,inputs:{"STEPS": [3, "$+[cA]uGMM3toj%TASoL", [4, "10"]]},fields:{}});
gg_list[55].push({num:295,level:13,sp_name:'Cat',code:'probo_cube_acceleration',one_hot:117,inputs:{},fields:{"PRO_CUBE_AXIS_ANALOG": ["X", null]}});
gg_list[55].push({num:296,level:13,sp_name:'Cat',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [2, "wd85Ni!o8F6n-1(s!.^_"]},fields:{}});
gg_list[55].push({num:297,level:13,sp_name:'Cat',code:'probo_cube_btn_digital',one_hot:113,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}});
gg_list[55].push({num:298,level:13,sp_name:'Cat',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [2, "H`QZqK]QFuSL,`![zJ{%"]},fields:{}});
gg_list[55].push({num:299,level:13,sp_name:'Cat',code:'probo_cube_accel_motion',one_hot:114,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "k/88e[eBZwBfP38p7tsm"]},fields:{"MOTIONSEL": ["0", null]}});
gg_list[56]=[{num:300,level:13,sp_name:'Cat',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[56].push({num:301,level:13,sp_name:'Cat',code:'probo_cube_expansion_type_set',one_hot:130,inputs:{},fields:{"PRO_CUBE_SENSER_SEL": ["1", null]}});
gg_list[56].push({num:302,level:13,sp_name:'Cat',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [3, "c-UaY#y$:HaR}gQc;f5t", [4, "10"]]},fields:{}});
gg_list[56].push({num:303,level:13,sp_name:'Cat',code:'probo_cube_expansion_value',one_hot:134,inputs:{},fields:{"PRO_CUBE_SENSER_VALUE_TYPE": ["1", null]}});
gg_list[56].push({num:304,level:13,sp_name:'Cat',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [3, "b)]q8=,N}BS92P+!#)6^", [4, "10"]]},fields:{}});
gg_list[56].push({num:305,level:13,sp_name:'Cat',code:'probo_cube_compass_value',one_hot:137,inputs:{},fields:{"PRO_CUBE_SENSER_VALUE_TYPE": ["1", null]}});
gg_list[56].push({num:306,level:13,sp_name:'Cat',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [2, "gQ%?KBBeoexr6uZD=*(O"]},fields:{}});
gg_list[56].push({num:307,level:13,sp_name:'Cat',code:'probo_cube_expansion_digital',one_hot:132,inputs:{},fields:{"PRO_CUBE_DIGITAL": ["D", null]}});
gg_list[56].push({num:308,level:13,sp_name:'Cat',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [2, "oqwd;/f+vWYXLjmmEyt9"]},fields:{}});
gg_list[56].push({num:309,level:13,sp_name:'Cat',code:'probo_cube_compass_direction',one_hot:138,inputs:{},fields:{"PRO_CUBE_DIRECTION": ["0", null]}});
gg_list[57]=[{num:310,level:14,sp_name:'Nemo2',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [1, [4, "10"]]},fields:{}}];
gg_list[57].push({num:311,level:14,sp_name:'Nemo2',code:'motion_backmovesteps',one_hot:2,inputs:{"STEPS": [1, [4, "10"]]},fields:{}});
gg_list[57].push({num:312,level:14,sp_name:'Nemo2',code:'motion_turnright',one_hot:3,inputs:{"DEGREES": [1, [4, "15"]]},fields:{}});
gg_list[57].push({num:313,level:14,sp_name:'Nemo2',code:'motion_turnleft',one_hot:4,inputs:{"DEGREES": [1, [4, "15"]]},fields:{}});
gg_list[57].push({num:314,level:14,sp_name:'Nemo2',code:'motion_goto',one_hot:5,inputs:{"TO": [1, "+NHM+FWhJd0rDtIINi8s"]},fields:{"TO": ["_random_"]}});
gg_list[58]=[{num:315,level:14,sp_name:'Nemo2',code:'motion_gotoxy',one_hot:6,inputs:{"X": [1, [4, "0"]], "Y": [1, [4, "0"]]},fields:{}}];
gg_list[58].push({num:316,level:14,sp_name:'Nemo2',code:'motion_glideto',one_hot:7,inputs:{"SECS": [1, [4, "1"]], "TO": [1, "yjz1wuzH@;;ETQ@k=KNi"]},fields:{"TO": ["_random_"]}});
gg_list[58].push({num:317,level:14,sp_name:'Nemo2',code:'motion_glidesecstoxy',one_hot:8,inputs:{"SECS": [1, [4, "1"]], "X": [1, [4, "0"]], "Y": [1, [4, "0"]]},fields:{}});
gg_list[58].push({num:318,level:14,sp_name:'Nemo2',code:'motion_pointindirection',one_hot:9,inputs:{"DIRECTION": [1, [8, "90"]]},fields:{}});
gg_list[58].push({num:319,level:14,sp_name:'Nemo2',code:'motion_pointtowards',one_hot:10,inputs:{"TOWARDS": [1, "kIPBRcZMQ~qvL?Z]5+`7"]},fields:{"TOWARDS": ["_mouse_"]}});
gg_list[59]=[{num:320,level:14,sp_name:'Nemo2',code:'motion_changexby',one_hot:11,inputs:{"DX": [3, "i~(S:5G;d!M_]:yuuAgD", [4, "10"]]},fields:{}}];
gg_list[59].push({num:321,level:14,sp_name:'Nemo2',code:'motion_xposition',one_hot:17,inputs:{},fields:{}});
gg_list[59].push({num:322,level:14,sp_name:'Nemo2',code:'motion_setx',one_hot:12,inputs:{"X": [3, "VV1~p,Rf_RoR*QAPXm60", [4, "0"]]},fields:{}});
gg_list[59].push({num:323,level:14,sp_name:'Nemo2',code:'motion_yposition',one_hot:18,inputs:{},fields:{}});
gg_list[59].push({num:324,level:14,sp_name:'Nemo2',code:'motion_changeyby',one_hot:13,inputs:{"DY": [3, "k6L^-)IUdic01B,R@07F", [4, "10"]]},fields:{}});
gg_list[59].push({num:325,level:14,sp_name:'Nemo2',code:'motion_direction',one_hot:19,inputs:{},fields:{}});
gg_list[59].push({num:326,level:14,sp_name:'Nemo2',code:'motion_sety',one_hot:14,inputs:{"Y": [1, [4, "0"]]},fields:{}});
gg_list[59].push({num:327,level:14,sp_name:'Nemo2',code:'motion_ifonedgebounce',one_hot:15,inputs:{},fields:{}});
gg_list[59].push({num:328,level:14,sp_name:'Nemo2',code:'motion_setrotationstyle',one_hot:16,inputs:{},fields:{"STYLE": ["left-right"]}});
gg_list[60]=[{num:329,level:14,sp_name:'Nemo2',code:'looks_sayforsecs',one_hot:20,inputs:{"MESSAGE": [1, [10, "\uc548\ub155!"]], "SECS": [1, [4, "2"]]},fields:{}}];
gg_list[60].push({num:330,level:14,sp_name:'Nemo2',code:'looks_say',one_hot:21,inputs:{"MESSAGE": [1, [10, "\uc548\ub155!"]]},fields:{}});
gg_list[60].push({num:331,level:14,sp_name:'Nemo2',code:'looks_thinkforsecs',one_hot:22,inputs:{"MESSAGE": [1, [10, "\uc74c..."]], "SECS": [1, [4, "2"]]},fields:{}});
gg_list[60].push({num:332,level:14,sp_name:'Nemo2',code:'looks_think',one_hot:23,inputs:{"MESSAGE": [1, [10, "\uc74c..."]]},fields:{}});
gg_list[61]=[{num:333,level:14,sp_name:'Nemo2',code:'looks_switchcostumeto',one_hot:24,inputs:{"COSTUME": [1, "/lw#,{Uq|4PDU{7e#Sjc"]},fields:{"COSTUME": ["Nemo01"]}}];
gg_list[61].push({num:334,level:14,sp_name:'Nemo2',code:'looks_nextcostume',one_hot:25,inputs:{},fields:{}});
gg_list[61].push({num:335,level:14,sp_name:'Nemo2',code:'looks_switchbackdropto',one_hot:26,inputs:{"BACKDROP": [1, "Jco(=OE*#52BfBLh!@G6"]},fields:{"BACKDROP": ["배경 1"]}});
gg_list[61].push({num:336,level:14,sp_name:'Nemo2',code:'looks_nextbackdrop',one_hot:27,inputs:{},fields:{}});
gg_list[61].push({num:337,level:14,sp_name:'Nemo2',code:'looks_changesizeby',one_hot:28,inputs:{"CHANGE": [1, [4, "10"]]},fields:{}});
gg_list[61].push({num:338,level:14,sp_name:'Nemo2',code:'looks_setsizeto',one_hot:29,inputs:{"SIZE": [1, [4, "100"]]},fields:{}});
gg_list[62]=[{num:339,level:14,sp_name:'Nemo2',code:'looks_changeeffectby',one_hot:30,inputs:{"CHANGE": [3, "!E[w)ZN3^@UbKbX-di@l", [4, "25"]]},fields:{"EFFECT": ["COLOR"]}}];
gg_list[62].push({num:340,level:14,sp_name:'Nemo2',code:'looks_costumenumbername',one_hot:37,inputs:{},fields:{"NUMBER_NAME": ["number"]}});
gg_list[62].push({num:341,level:14,sp_name:'Nemo2',code:'looks_seteffectto',one_hot:31,inputs:{"VALUE": [3, "LOY(%YJHY5{+B0+s41{]", [4, "0"]]},fields:{"EFFECT": ["COLOR"]}});
gg_list[62].push({num:342,level:14,sp_name:'Nemo2',code:'looks_backdropnumbername',one_hot:38,inputs:{},fields:{"NUMBER_NAME": ["number"]}});
gg_list[62].push({num:343,level:14,sp_name:'Nemo2',code:'looks_cleargraphiceffects',one_hot:32,inputs:{},fields:{}});
gg_list[62].push({num:344,level:14,sp_name:'Nemo2',code:'looks_show',one_hot:33,inputs:{},fields:{}});
gg_list[62].push({num:345,level:14,sp_name:'Nemo2',code:'looks_hide',one_hot:34,inputs:{},fields:{}});
gg_list[62].push({num:346,level:14,sp_name:'Nemo2',code:'looks_gotofrontback',one_hot:35,inputs:{},fields:{"FRONT_BACK": ["front"]}});
gg_list[62].push({num:347,level:14,sp_name:'Nemo2',code:'looks_goforwardbackwardlayers',one_hot:36,inputs:{"NUM": [3, "jWaOO1SK9%3pyEyRj)Gn", [7, "1"]]},fields:{"FORWARD_BACKWARD": ["forward"]}});
gg_list[62].push({num:348,level:14,sp_name:'Nemo2',code:'looks_size',one_hot:39,inputs:{},fields:{}});
gg_list[63]=[{num:349,level:14,sp_name:'Nemo2',code:'sound_playuntildone',one_hot:40,inputs:{"SOUND_MENU": [1, "U=5pv!Mg*2uTsZiX7gvt"]},fields:{"SOUND_MENU": ["pop"]}}];
gg_list[63].push({num:350,level:14,sp_name:'Nemo2',code:'sound_play',one_hot:41,inputs:{"SOUND_MENU": [1, "PKVedijrW:Qr,fD=.;(V"]},fields:{"SOUND_MENU": ["pop"]}});
gg_list[63].push({num:351,level:14,sp_name:'Nemo2',code:'sound_stopallsounds',one_hot:42,inputs:{},fields:{}});
gg_list[63].push({num:352,level:14,sp_name:'Nemo2',code:'sound_changeeffectby',one_hot:43,inputs:{"VALUE": [1, [4, "10"]]},fields:{"EFFECT": ["PITCH"]}});
gg_list[63].push({num:353,level:14,sp_name:'Nemo2',code:'sound_seteffectto',one_hot:44,inputs:{"VALUE": [1, [4, "100"]]},fields:{"EFFECT": ["PITCH"]}});
gg_list[63].push({num:354,level:14,sp_name:'Nemo2',code:'sound_cleareffects',one_hot:45,inputs:{},fields:{}});
gg_list[63].push({num:355,level:14,sp_name:'Nemo2',code:'sound_changevolumeby',one_hot:46,inputs:{"VOLUME": [1, [4, "-10"]]},fields:{}});
gg_list[63].push({num:356,level:14,sp_name:'Nemo2',code:'sound_setvolumeto',one_hot:47,inputs:{"VOLUME": [3, "*:pi~4R[.5e9@-X3kP%t", [4, "100"]]},fields:{}});
gg_list[63].push({num:357,level:14,sp_name:'Nemo2',code:'sound_volume',one_hot:48,inputs:{},fields:{}});
gg_list[64]=[{num:358,level:14,sp_name:'Nemo2',code:'motion_movesteps',one_hot:1,inputs:{"STEPS": [1, [4, "10"]]},fields:{}}];
gg_list[64].push({num:359,level:14,sp_name:'Nemo2',code:'motion_backmovesteps',one_hot:2,inputs:{"STEPS": [1, [4, "10"]]},fields:{}});
gg_list[64].push({num:360,level:14,sp_name:'Nemo2',code:'motion_turnright',one_hot:3,inputs:{"DEGREES": [1, [4, "15"]]},fields:{}});
gg_list[64].push({num:361,level:14,sp_name:'Nemo2',code:'motion_turnleft',one_hot:4,inputs:{"DEGREES": [1, [4, "15"]]},fields:{}});
gg_list[64].push({num:362,level:14,sp_name:'Nemo2',code:'motion_goto',one_hot:5,inputs:{"TO": [1, "PPz:9:)GAD2LG/SSYZpR"]},fields:{"TO": ["_random_"]}});
gg_list[65]=[{num:363,level:15,sp_name:'Nemo3',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[65].push({num:364,level:15,sp_name:'Nemo3',code:'control_if',one_hot:61,inputs:{},fields:{}});
gg_list[65].push({num:365,level:15,sp_name:'Nemo3',code:'control_if_else',one_hot:62,inputs:{},fields:{}});
gg_list[65].push({num:366,level:15,sp_name:'Nemo3',code:'control_wait_until',one_hot:63,inputs:{},fields:{}});
gg_list[65].push({num:367,level:15,sp_name:'Nemo3',code:'control_repeat_until',one_hot:64,inputs:{},fields:{}});
gg_list[65].push({num:368,level:15,sp_name:'Nemo3',code:'control_stop',one_hot:65,inputs:{},fields:{"STOP_OPTION": ["all", null]}});
gg_list[66]=[{num:369,level:15,sp_name:'Nemo3',code:'event_whenkeypressed',one_hot:50,inputs:{},fields:{"KEY_OPTION": ["space", null]}}];
gg_list[66].push({num:370,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "1"]]},fields:{}});
gg_list[66].push({num:371,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "1"]]},fields:{}});
gg_list[67]=[{num:372,level:15,sp_name:'Nemo3',code:'event_whenthisspriteclicked',one_hot:51,inputs:{},fields:{}}];
gg_list[67].push({num:373,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "1"]]},fields:{}});
gg_list[67].push({num:374,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "1"]]},fields:{}});
gg_list[68]=[{num:375,level:15,sp_name:'Nemo3',code:'event_whenbackdropswitchesto',one_hot:52,inputs:{},fields:{"BACKDROP": ["배경 1", null]}}];
gg_list[68].push({num:376,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "1"]]},fields:{}});
gg_list[68].push({num:377,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "1"]]},fields:{}});
gg_list[69]=[{num:378,level:15,sp_name:'Nemo3',code:'event_whengreaterthan',one_hot:53,inputs:{"VALUE": [1, [4, "10"]]},fields:{"WHENGREATERTHANMENU": ["LOUDNESS", null]}}];
gg_list[69].push({num:379,level:15,sp_name:'Nemo3',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [3, "y@#jsZETX7R.n/]gOC=L", null]},fields:{}});
gg_list[69].push({num:380,level:15,sp_name:'Nemo3',code:'sensing_touchingobject',one_hot:69,inputs:{"TOUCHINGOBJECTMENU": [1, "-,(/a.{P%:Cu=T9h@*m."]},fields:{"TOUCHINGOBJECTMENU": ["_mouse_", null]}});
gg_list[69].push({num:381,level:15,sp_name:'Nemo3',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [3, "r9}OE^E4mXJ,b3[~z[9k", null]},fields:{}});
gg_list[69].push({num:382,level:15,sp_name:'Nemo3',code:'sensing_mousedown',one_hot:76,inputs:{},fields:{}});
gg_list[69].push({num:383,level:15,sp_name:'Nemo3',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [3, "a^X6~O0eUKb%WM:);ofR", null]},fields:{}});
gg_list[69].push({num:384,level:15,sp_name:'Nemo3',code:'sensing_touchingcolor',one_hot:70,inputs:{"COLOR": [1, [9, "#825e67"]]},fields:{}});
gg_list[69].push({num:385,level:15,sp_name:'Nemo3',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [3, "38FT9X*lPp!kCS#98j8e", null]},fields:{}});
gg_list[69].push({num:386,level:15,sp_name:'Nemo3',code:'sensing_coloristouchingcolor',one_hot:71,inputs:{"COLOR": [1, [9, "#30f1a3"]], "COLOR2": [1, [9, "#48e3b4"]]},fields:{}});
gg_list[69].push({num:387,level:15,sp_name:'Nemo3',code:'sensing_askandwait',one_hot:73,inputs:{"QUESTION": [3, "e}iLTIkNAMibsQ@*},B{", [10, "What's your name?"]]},fields:{}});
gg_list[69].push({num:388,level:15,sp_name:'Nemo3',code:'sensing_loudness',one_hot:80,inputs:{},fields:{}});
gg_list[69].push({num:389,level:15,sp_name:'Nemo3',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [3, "~DG_K@Q!{H|j?QSyD*2w", null]},fields:{}});
gg_list[69].push({num:390,level:15,sp_name:'Nemo3',code:'sensing_keypressed',one_hot:75,inputs:{"KEY_OPTION": [1, "TEFKhqNlh`4ua|U*?wVO"]},fields:{"KEY_OPTION": ["space", null]}});
gg_list[70]=[{num:391,level:15,sp_name:'Nemo3',code:'event_whenbroadcastreceived',one_hot:54,inputs:{},fields:{"BROADCAST_OPTION": ["메시지1", "u/_zNk=AddLnnbIxrPJj"]}}];
gg_list[70].push({num:392,level:15,sp_name:'Nemo3',code:'event_broadcast',one_hot:55,inputs:{"BROADCAST_INPUT": [1, [11, "\uba54\uc2dc\uc9c01", "u/_zNk=AddLnnbIxrPJj"]]},fields:{}});
gg_list[70].push({num:393,level:15,sp_name:'Nemo3',code:'event_broadcastandwait',one_hot:56,inputs:{"BROADCAST_INPUT": [1, [11, "\uba54\uc2dc\uc9c01", "u/_zNk=AddLnnbIxrPJj"]]},fields:{}});
gg_list[70].push({num:394,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [1, [5, "1"]]},fields:{}});
gg_list[70].push({num:395,level:15,sp_name:'Nemo3',code:'control_repeat',one_hot:58,inputs:{"TIMES": [1, [6, "10"]]},fields:{}});
gg_list[70].push({num:396,level:15,sp_name:'Nemo3',code:'control_forever',one_hot:59,inputs:{},fields:{}});
gg_list[70].push({num:397,level:15,sp_name:'Nemo3',code:'control_do_break',one_hot:60,inputs:{},fields:{}});
gg_list[71]=[{num:398,level:15,sp_name:'Nemo3',code:'control_start_as_clone',one_hot:66,inputs:{},fields:{}}];
gg_list[71].push({num:399,level:15,sp_name:'Nemo3',code:'control_create_clone_of',one_hot:67,inputs:{"CLONE_OPTION": [1, "E#b,58:d=hh*wWD5u}3|"]},fields:{"CLONE_OPTION": ["_myself_", null]}});
gg_list[71].push({num:400,level:15,sp_name:'Nemo3',code:'control_delete_this_clone',one_hot:68,inputs:{},fields:{}});
gg_list[72]=[{num:401,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "9JRc4xdP]hWzcaV3{A]y", [5, "1"]]},fields:{}}];
gg_list[72].push({num:402,level:15,sp_name:'Nemo3',code:'sensing_distanceto',one_hot:72,inputs:{"DISTANCETOMENU": [1, "iA1:3FUR3h%XuCIse09~"]},fields:{"DISTANCETOMENU": ["_mouse_", null]}});
gg_list[72].push({num:403,level:15,sp_name:'Nemo3',code:'sensing_setdragmode',one_hot:79,inputs:{},fields:{"DRAG_MODE": ["draggable", null]}});
gg_list[72].push({num:404,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "*Xk5f8Pi9(;tS{C;ALNN", [5, "1"]]},fields:{}});
gg_list[72].push({num:405,level:15,sp_name:'Nemo3',code:'sensing_answer',one_hot:74,inputs:{},fields:{}});
gg_list[72].push({num:406,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "Owdr{Z*ZalO0FX!W4}=-", [5, "1"]]},fields:{}});
gg_list[72].push({num:407,level:15,sp_name:'Nemo3',code:'sensing_timer',one_hot:81,inputs:{},fields:{}});
gg_list[72].push({num:408,level:15,sp_name:'Nemo3',code:'sensing_resettimer',one_hot:82,inputs:{},fields:{}});
gg_list[73]=[{num:409,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "IeXD_ukhPDv{_#cGL%3:", [5, "1"]]},fields:{}}];
gg_list[73].push({num:410,level:15,sp_name:'Nemo3',code:'sensing_of',one_hot:83,inputs:{"OBJECT": [1, ",V{EDmi;AZ{%l}GY(af!"]},fields:{"PROPERTY": ["backdrop #", null],"OBJECT": ["_stage_", null]}});
gg_list[73].push({num:411,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "uyEG8Rd_.{u8kF__M!gr", [5, "1"]]},fields:{}});
gg_list[73].push({num:412,level:15,sp_name:'Nemo3',code:'sensing_current',one_hot:84,inputs:{},fields:{"CURRENTMENU": ["YEAR", null]}});
gg_list[73].push({num:413,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "erOvjdHIoOFrC];giLy*", [5, "1"]]},fields:{}});
gg_list[73].push({num:414,level:15,sp_name:'Nemo3',code:'sensing_dayssince2000',one_hot:85,inputs:{},fields:{}});
gg_list[73].push({num:415,level:15,sp_name:'Nemo3',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "]2Lq.kIbIdwaoMI/+evF", [5, "1"]]},fields:{}});
gg_list[73].push({num:416,level:15,sp_name:'Nemo3',code:'sensing_username',one_hot:86,inputs:{},fields:{}});
gg_list[74]=[{num:417,level:16,sp_name:'Nemo4',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[74].push({num:418,level:16,sp_name:'Nemo4',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "jboXm_kX1/_*gZ3!A-XG", [5, "1"]]},fields:{}});
gg_list[74].push({num:419,level:16,sp_name:'Nemo4',code:'operator_add',one_hot:87,inputs:{"NUM1": [1, [4, "2"]], "NUM2": [1, [4, "2"]]},fields:{}});
gg_list[74].push({num:420,level:16,sp_name:'Nemo4',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "ejKz)*1K#_=+nm4.2z?_", [5, "1"]]},fields:{}});
gg_list[74].push({num:421,level:16,sp_name:'Nemo4',code:'operator_subtract',one_hot:88,inputs:{"NUM1": [1, [4, "3"]], "NUM2": [1, [4, "3"]]},fields:{}});
gg_list[74].push({num:422,level:16,sp_name:'Nemo4',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "0;7yN3Z~Dz[9];oc(DOt", [5, "1"]]},fields:{}});
gg_list[74].push({num:423,level:16,sp_name:'Nemo4',code:'operator_multiply',one_hot:89,inputs:{"NUM1": [1, [4, "4"]], "NUM2": [1, [4, "4"]]},fields:{}});
gg_list[74].push({num:424,level:16,sp_name:'Nemo4',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "h4|%RKQTvE,p9g6:sE/L", [5, "1"]]},fields:{}});
gg_list[74].push({num:425,level:16,sp_name:'Nemo4',code:'operator_random',one_hot:91,inputs:{"FROM": [1, [4, "1"]], "TO": [1, [4, "10"]]},fields:{}});
gg_list[74].push({num:426,level:16,sp_name:'Nemo4',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "BFM8;6f6qzV)vNm_T.[}", [5, "1"]]},fields:{}});
gg_list[74].push({num:427,level:16,sp_name:'Nemo4',code:'operator_join',one_hot:98,inputs:{"STRING1": [1, [10, "apple "]], "STRING2": [1, [10, "banana"]]},fields:{}});
gg_list[74].push({num:428,level:16,sp_name:'Nemo4',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "bepK[Zf5O]q],Esk0n`]", [5, "1"]]},fields:{}});
gg_list[74].push({num:429,level:16,sp_name:'Nemo4',code:'operator_letter_of',one_hot:99,inputs:{"STRING": [1, [10, "apple"]], "LETTER": [1, [6, "1"]]},fields:{}});
gg_list[74].push({num:430,level:16,sp_name:'Nemo4',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "Yz`3VCbvp9#zmtYAL=1`", [5, "1"]]},fields:{}});
gg_list[74].push({num:431,level:16,sp_name:'Nemo4',code:'operator_length',one_hot:100,inputs:{"STRING": [1, [10, "apple"]]},fields:{}});
gg_list[74].push({num:432,level:16,sp_name:'Nemo4',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "[ZG-q-Fx4dzG-ATkC8De", [5, "1"]]},fields:{}});
gg_list[74].push({num:433,level:16,sp_name:'Nemo4',code:'operator_mod',one_hot:102,inputs:{"NUM1": [1, [4, "1"]], "NUM2": [1, [4, "1"]]},fields:{}});
gg_list[74].push({num:434,level:16,sp_name:'Nemo4',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "u0ZN~7PTh)H!8;8NmFBj", [5, "1"]]},fields:{}});
gg_list[74].push({num:435,level:16,sp_name:'Nemo4',code:'operator_round',one_hot:103,inputs:{"NUM": [1, [4, "0.5"]]},fields:{}});
gg_list[74].push({num:436,level:16,sp_name:'Nemo4',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "MXp|YrU44MU[OZ@xWZ#L", [5, "1"]]},fields:{}});
gg_list[74].push({num:437,level:16,sp_name:'Nemo4',code:'operator_mathop',one_hot:104,inputs:{"NUM": [1, [4, "55"]]},fields:{"OPERATOR": ["abs", null]}});
gg_list[75]=[{num:438,level:16,sp_name:'Nemo4',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[75].push({num:439,level:16,sp_name:'Nemo4',code:'data_setvariableto',one_hot:106,inputs:{"VALUE": [3, "dU~SBIZ%fAFQv7{3vOoS", [10, "0"]]},fields:{"VARIABLE": ["나의 변수", "`jEk@4|i[#Fk?(8x)AV.-my variable"]}});
gg_list[75].push({num:440,level:16,sp_name:'Nemo4',code:'data_operator_add',one_hot:110,inputs:{"VALUE": [1, [10, "0"]]},fields:{"VARIABLE": ["나의 변수", "`jEk@4|i[#Fk?(8x)AV.-my variable"]}});
gg_list[75].push({num:441,level:16,sp_name:'Nemo4',code:'data_changevariableby',one_hot:107,inputs:{"VALUE": [3, [12, "\ub098\uc758 \ubcc0\uc218", "`jEk@4|i[#Fk?(8x)AV.-my variable"], [4, "1"]]},fields:{"VARIABLE": ["나의 변수", "`jEk@4|i[#Fk?(8x)AV.-my variable"]}});
gg_list[75].push({num:442,level:16,sp_name:'Nemo4',code:'data_showvariable',one_hot:108,inputs:{},fields:{"VARIABLE": ["나의 변수", "`jEk@4|i[#Fk?(8x)AV.-my variable"]}});
gg_list[75].push({num:443,level:16,sp_name:'Nemo4',code:'data_hidevariable',one_hot:109,inputs:{},fields:{"VARIABLE": ["나의 변수", "`jEk@4|i[#Fk?(8x)AV.-my variable"]}});
gg_list[76]=[{num:444,level:16,sp_name:'Nemo4',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[76].push({num:445,level:16,sp_name:'Nemo4',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [3, "TZ:Y88#0dRD:|+SeIEY8", null]},fields:{}});
gg_list[76].push({num:446,level:16,sp_name:'Nemo4',code:'operator_and',one_hot:95,inputs:{"OPERAND1": [3, "GL(w:HW2ad=5WT3L%h?[", null], "OPERAND2": [3, "yTEunO60WC,Wg5;?IK9V", null]},fields:{}});
gg_list[76].push({num:447,level:16,sp_name:'Nemo4',code:'operator_gt',one_hot:92,inputs:{"OPERAND1": [1, [10, "1"]], "OPERAND2": [1, [10, "50"]]},fields:{}});
gg_list[76].push({num:448,level:16,sp_name:'Nemo4',code:'operator_lt',one_hot:93,inputs:{"OPERAND1": [1, [10, "2"]], "OPERAND2": [1, [10, "50"]]},fields:{}});
gg_list[76].push({num:449,level:16,sp_name:'Nemo4',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [3, "(A2vVuCSKL}HZBwVSZ0G", null]},fields:{}});
gg_list[76].push({num:450,level:16,sp_name:'Nemo4',code:'operator_or',one_hot:96,inputs:{"OPERAND1": [3, "_ULzXU7X14N~Q+aoJ/}u", null], "OPERAND2": [3, "x-X^kb/R~l56?3A-p!M9", null]},fields:{}});
gg_list[76].push({num:451,level:16,sp_name:'Nemo4',code:'operator_equals',one_hot:94,inputs:{"OPERAND1": [1, [10, "3"]], "OPERAND2": [1, [10, "50"]]},fields:{}});
gg_list[76].push({num:452,level:16,sp_name:'Nemo4',code:'operator_contains',one_hot:101,inputs:{"STRING1": [1, [10, "apple"]], "STRING2": [1, [10, "a"]]},fields:{}});
gg_list[76].push({num:453,level:16,sp_name:'Nemo4',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [3, "LK{j9Q^f02#[v0eqx4P;", null]},fields:{}});
gg_list[76].push({num:454,level:16,sp_name:'Nemo4',code:'operator_not',one_hot:97,inputs:{"OPERAND": [3, "X~ke(K)BNom,K9[K6JrL", null]},fields:{}});
gg_list[76].push({num:455,level:16,sp_name:'Nemo4',code:'operator_gt',one_hot:92,inputs:{"OPERAND1": [1, [10, "2"]], "OPERAND2": [1, [10, "50"]]},fields:{}});
gg_list[77]=[{num:456,level:17,sp_name:'Nemo5',code:'probo_cube_whenpressed_digital',one_hot:111,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}}];
gg_list[77].push({num:457,level:17,sp_name:'Nemo5',code:'probo_cube_selecter',one_hot:120,inputs:{"CUBE_LED_IDX": [1, "vb).d(P5]..]LxB30|_c"], "CUBE_SPEEDS": [1, "Uxs.EY#,azZ3rOV|8Xut"]},fields:{"CUBE_SPEEDS": ["0", null],"SELECTER": ["0", null]}});
gg_list[77].push({num:458,level:17,sp_name:'Nemo5',code:'probo_cube_picker',one_hot:121,inputs:{"CUBE_LED_DATA": [1, "/Dbiq/A@}x*OpL}B5|ZG"], "CUBE_SPEEDS": [1, "j:W-D[M{49[G|1o^p@@b"]},fields:{"CUBE_SPEEDS": ["0", null],"PICKER": ["0000000000000000000000000000", null]}});
gg_list[77].push({num:459,level:17,sp_name:'Nemo5',code:'probo_cube_mellody_playtoend',one_hot:126,inputs:{},fields:{"PRO_CUBE_MELODY": ["1", null]}});
gg_list[77].push({num:460,level:17,sp_name:'Nemo5',code:'probo_cube_note',one_hot:127,inputs:{"NOTE": [1, "y]rE78tQ9Y}%J!TIO%(j"]},fields:{"PROBO_NOTE": ["0", null]}});
gg_list[77].push({num:461,level:17,sp_name:'Nemo5',code:'probo_cube_note_sec',one_hot:128,inputs:{"NOTE": [1, "|4|%t#qPNeQ#w5UZd9sA"], "SEC": [1, "|}~yr{Fp(XV9A+#Y](.N"]},fields:{"NUM6S": [" 1 ", null],"PROBO_NOTE": ["0", null]}});
gg_list[78]=[{num:462,level:17,sp_name:'Nemo5',code:'probo_cube_whenpressed_motion',one_hot:112,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "Vx=0MwX=*jz{{o,WN9Bm"]},fields:{"MOTIONSEL": ["0", null]}}];
gg_list[78].push({num:463,level:17,sp_name:'Nemo5',code:'probo_cube_text',one_hot:122,inputs:{"CUBE_LED_TEXT": [1, [10, "Hello"]], "CUBE_SPEEDS": [1, "v`Gp8#A^7v~Nje;@~}i9"]},fields:{"CUBE_SPEEDS": ["1", null]}});
gg_list[78].push({num:464,level:17,sp_name:'Nemo5',code:'probo_cube_clear',one_hot:123,inputs:{},fields:{}});
gg_list[78].push({num:465,level:17,sp_name:'Nemo5',code:'probo_cube_pixel',one_hot:124,inputs:{"PIXELX": [1, [4, " 0 "]], "PIXELY": [1, [4, " 0 "]], "PRO_ONOFF": [1, "n3XInON^~U.mot1JSQUu"]},fields:{"PRO_ONOFF": ["0", null]}});
gg_list[78].push({num:466,level:17,sp_name:'Nemo5',code:'probo_cube_mellody_play',one_hot:125,inputs:{},fields:{"PRO_CUBE_MELODY": ["1", null]}});
gg_list[78].push({num:467,level:17,sp_name:'Nemo5',code:'probo_cube_sound_stop',one_hot:129,inputs:{},fields:{}});
gg_list[79]=[{num:468,level:17,sp_name:'Nemo5',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[79].push({num:469,level:17,sp_name:'Nemo5',code:'probo_cube_expansion_type_set',one_hot:130,inputs:{},fields:{"PRO_CUBE_SENSER_SEL": ["1", null]}});
gg_list[79].push({num:470,level:17,sp_name:'Nemo5',code:'probo_cube_expansion_analog_set',one_hot:131,inputs:{"VALUE": [1, [4, " 0 "]]},fields:{}});
gg_list[79].push({num:471,level:17,sp_name:'Nemo5',code:'probo_cube_compass_analog_set',one_hot:135,inputs:{"VALUE": [1, [4, " 0 "]]},fields:{}});
gg_list[80]=[{num:472,level:17,sp_name:'Nemo5',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[80].push({num:473,level:17,sp_name:'Nemo5',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "H,e-(YX3{;Qar!11Qfu=", [5, "1"]]},fields:{}});
gg_list[80].push({num:474,level:17,sp_name:'Nemo5',code:'probo_cube_btn_analog',one_hot:116,inputs:{},fields:{"PRO_CUBE_SWITCH_ANALOG": ["SA1", null]}});
gg_list[80].push({num:475,level:17,sp_name:'Nemo5',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "z5q^EwY#5+y`:ohBzz8^", [5, "1"]]},fields:{}});
gg_list[80].push({num:476,level:17,sp_name:'Nemo5',code:'probo_cube_acceleration',one_hot:117,inputs:{},fields:{"PRO_CUBE_AXIS_ANALOG": ["X", null]}});
gg_list[80].push({num:477,level:17,sp_name:'Nemo5',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "NZgxv,PV/x!N+MclCyv%", [5, "1"]]},fields:{}});
gg_list[80].push({num:478,level:17,sp_name:'Nemo5',code:'probo_cube_illuminance',one_hot:118,inputs:{},fields:{}});
gg_list[80].push({num:479,level:17,sp_name:'Nemo5',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "bE,O}c~I2,kTo{T#SDrs", [5, "1"]]},fields:{}});
gg_list[80].push({num:480,level:17,sp_name:'Nemo5',code:'probo_cube_mapping',one_hot:119,inputs:{"PRO_CUBE_INPUT_DATA": [1, [4, " 0 "]], "PRO_INPUT0": [1, [4, " 0 "]], "PRO_INPUT1": [1, [4, " 0 "]], "PRO_OUTPUT0": [1, [4, " 0 "]], "PRO_OUTPUT1": [1, [4, " 0 "]]},fields:{}});
gg_list[80].push({num:481,level:17,sp_name:'Nemo5',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "mF7id?|k_i,CRjsoJM`v", [5, "1"]]},fields:{}});
gg_list[80].push({num:482,level:17,sp_name:'Nemo5',code:'probo_cube_expansion_analog',one_hot:133,inputs:{},fields:{}});
gg_list[80].push({num:483,level:17,sp_name:'Nemo5',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "s,^|c?zEe;N?mHc|t0`9", [5, "1"]]},fields:{}});
gg_list[80].push({num:484,level:17,sp_name:'Nemo5',code:'probo_cube_expansion_value',one_hot:134,inputs:{},fields:{"PRO_CUBE_SENSER_VALUE_TYPE": ["1", null]}});
gg_list[80].push({num:485,level:17,sp_name:'Nemo5',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "0NJnD%,%1t9G%cxc2/[d", [5, "1"]]},fields:{}});
gg_list[80].push({num:486,level:17,sp_name:'Nemo5',code:'probo_cube_compass_analog',one_hot:136,inputs:{},fields:{}});
gg_list[80].push({num:487,level:17,sp_name:'Nemo5',code:'control_wait',one_hot:57,inputs:{"DURATION": [3, "l6!lu-H-s{C208RQ`h_.", [5, "1"]]},fields:{}});
gg_list[80].push({num:488,level:17,sp_name:'Nemo5',code:'probo_cube_compass_value',one_hot:137,inputs:{},fields:{"PRO_CUBE_SENSER_VALUE_TYPE": ["1", null]}});
gg_list[81]=[{num:489,level:17,sp_name:'Nemo5',code:'event_whenflagclicked',one_hot:49,inputs:{},fields:{}}];
gg_list[81].push({num:490,level:17,sp_name:'Nemo5',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [3, "7Pi!1f;Ow6sZbLGM6Bwe", null]},fields:{}});
gg_list[81].push({num:491,level:17,sp_name:'Nemo5',code:'probo_cube_btn_digital',one_hot:113,inputs:{},fields:{"PRO_CUBE_SWITCH": ["SD1", null], "PRO_CUBE_DIGITAL": ["D", null]}});
gg_list[81].push({num:492,level:17,sp_name:'Nemo5',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [3, "gs4=Cj.8E:nv+OK3oi;:", null]},fields:{}});
gg_list[81].push({num:493,level:17,sp_name:'Nemo5',code:'probo_cube_accel_motion',one_hot:114,inputs:{"PRO_CUBE_AXIS_MOTION": [1, "}U]g[)L^{s5O3.g:gpYQ"]},fields:{"MOTIONSEL": ["0", null]}});
gg_list[81].push({num:494,level:17,sp_name:'Nemo5',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [3, "8JmOex;ENGrCfr0gp%Jj", null]},fields:{}});
gg_list[81].push({num:495,level:17,sp_name:'Nemo5',code:'probo_cube_pixel_read',one_hot:115,inputs:{"PIXELX": [1, [4, " 0 "]], "PIXELY": [1, [4, " 0 "]]},fields:{}});
gg_list[81].push({num:496,level:17,sp_name:'Nemo5',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [3, "N8KwC=nm)TIU.S,:zN!3", null]},fields:{}});
gg_list[81].push({num:497,level:17,sp_name:'Nemo5',code:'probo_cube_expansion_digital',one_hot:132,inputs:{},fields:{"PRO_CUBE_DIGITAL": ["D", null]}});
gg_list[81].push({num:498,level:17,sp_name:'Nemo5',code:'control_wait_until',one_hot:63,inputs:{"CONDITION": [3, "G^{Y)uSfwa;d9l#?8Tbx", null]},fields:{}});
gg_list[81].push({num:499,level:17,sp_name:'Nemo5',code:'probo_cube_compass_direction',one_hot:138,inputs:{},fields:{"PRO_CUBE_DIRECTION": ["0", null]}});
